version: '3'
services:
  web:
    image: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    container_name: odoo_db
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
volumes:
   odoo-web-data:
   odoo-db-data:

